sudo: required

language: java

services:
  - docker
  
before_install:
    - chmod +x mvnw
    - docker build -t sinch5/spring-cloud-config-server -f Dockerfile.dev .

script:
    - docker run sinch5/spring-cloud-config-server mvn test
    
after_success:
    - docker build -t sinch5/spring-cloud-config-server .
    
    
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: spring-cloud-config-server
    env: SpringCloudConfigServer-env
    bucket_name: elasticbeanstalk-us-east-1-608067911170
    bucket_path: /config-server
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY